# -*- coding: utf-8 -*-
"""[DM] - Asosiasi_Penjualan Jilbab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dSNW6p4lYZjhfCUO_wSS8uvFmRVXhnGQ
"""

!pip install apriori_python

!pip install apyori

import pandas as pd
import numpy as np
from apriori_python import apriori as ap
from apyori import apriori as apr

jual = pd.read_csv("/content/Jilbab.csv")
jual

jual.index = jual["Transaksi"]
jual = jual.drop(["Transaksi"], axis=1)
jual

#ubah ke dalam array
item = []

for i in range(len(jual)):
  item.append([str(jual.values[i,j]) for j in range(6)])

item

freItemSet, rules = ap(item, minSup=0.2, minConf=0.7)
rules[0]

tabel_rule = pd.DataFrame(data=rules,
                          columns = ['Jika Ada Itemset-',
                                      'maka beli itemset-',
                                      'minimum confidence'])
tabel_rule

asosiasi = apr(item,
               min_length=2,        
               min_support=0.2,
               min_confidence=0.7,
               min_lift=1)

#Mengubah ke dalam bentuk list
asosiasi = list(asosiasi)
#Melihat seluruh pola yang terbentuk
asosiasi

rule = pd.DataFrame(data=asosiasi)
rule

for item in asosiasi:
  #first index of the inner list
  #contains base item and add item
  pair = item[0]
  items = [x for x in pair]
  print('Rule : ' + items[0] + " -> " + items[-1])

  #second index of the inner list
  print('Support : ' + str(item[1]))

  #thirs index of the list located at 0th
  #of the third index of the inner list
  print("Confidence : " + str(item[2][0][2]))
  print("Lift : " + str(item[2][0][3]))
  print("="*50)

